name: training
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # --- OpenStreetMap Packages (No API Key Required) ---
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  # ----------------------------------------------------

  # ADD THIS PACKAGE FOR CLUSTERING
  flutter_map_marker_cluster: ^1.3.2

  flutter_map_cache: ^1.4.0
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Ensure your JSON data file is registered here
  assets:
    - assets/lcp_data.json